version: "2.0"
services:
  app:
#    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN
    depends_on:
      - db
      - elasticsearch
      - redis
      - rabbitmq
      - jenkins
    ports:
      - "80:8080"
      - "10001:10001"
      - "222:222"
    environment:
      APPLICATION_ENV: dockersuite
      APPLICATION_STORE: DE
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: spryker
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
      POSTGRES_DATABASE: DE_dockersuite_zed
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PROTOCOL: redis
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_API_PORT: 15672
      RABBITMQ_USER: spryker
      RABBITMQ_PASSWORD: secret
      RABBITMQ_VHOST: /dockersuite
      YVES_HOST: www.de.demoshop.local
      YVES_PROTOCOL: http
      ZED_HOST: os.de.demoshop.local
      ZED_PROTOCOL: http
      JENKINS_HOST: jenkins
      JENKINS_PORT: 8080
      GLUE_HOST: glue.de.demoshop.local
      NEWRELIC_KEY: 5c2eyournewrelickey1111111111021cb198cee
      GITHUB_TOKEN: 8888yourgithubtoken8888
      PHP_CLI_RAM: 2048
      SMTP_HOST: 127.0.0.1
      SMTP_PORT: 25
      SMTP_USER: ''
      SMTP_PASS: ''
      SMTP_TLS: 'no'
      ZED_HTTPS_ON: 0
      ZED_HTTP_TO_HTTPS: 0
      YVES_HTTPS_ON: 0
      YVES_HTTP_TO_HTTPS: 0
      GLUE_HTTPS_ON: 0
      GLUE_HTTP_TO_HTTPS: 0
    volumes:
        - versions-sync:/versions:rw
        - static-sync:/static:rw

  db:
#    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_DB: DE_dockersuite_zed
      POSTGRES_USER: spryker
      POSTGRES_PASSWORD: secret

  elasticsearch:
#    restart: always
    image: elasticsearch:5.6
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  redis:
#    restart: always
    image: redis:3.2

  rabbitmq:
#    restart: always
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: spryker
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_DEFAULT_VHOST: /dockersuite
    ports:
      - "15672:15672"

  jenkins:
#    restart: always
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    environment:
      JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
      ZED_HOST: app
    ports:
      - "9090:8080"
    volumes:
      - jenkins-sync:/var/jenkins_home:rw

volumes:
  versions-sync:
    external: true
  static-sync:
    external: true
  jenkins-sync:
    external: true
