env:
  APPLICATION_ENV: staging

stores:
  - DE
  - US

sections:
  build:
    generate-transfers:
      command: "vendor/bin/console transfer:generate"
      stores:
        - DE
        - US

    twig-cache-warmup:
      command: "vendor/bin/console twig:cache:warmer"
      stores:
        - DE
        - US

    navigation-cache-warmup:
      command: "vendor/bin/console navigation:build-cache"
      stores:
        - DE
        - US

    rest-request-validation-cache-warmup:
      command: "vendor/bin/console glue:rest:build-request-validation-cache"
      stores:
        - DE
        - US

    propel-copy-schema:
      command: "vendor/bin/console propel:schema:copy"
      stores:
        - DE
        - US

    propel-build:
      command: "vendor/bin/console propel:model:build"
      stores:
        - DE
        - US

    generate-entity-transfer:
      command: "vendor/bin/console transfer:generate"
      stores:
        - DE
        - US

    generate-page-index-map:
      command: "vendor/bin/console search:setup:index-map"
      stores:
        - DE
        - US

    translator-generate-cache:
      command: "vendor/bin/console translator:generate-cache"
      stores:
        - DE
        - US


  build-static:
    dependencies-install:
      command: "vendor/bin/console frontend:project:install-dependencies"
      stores:
        - DE
        - US

    yves-install-dependencies:
      command: "vendor/bin/console frontend:yves:install-dependencies"
      stores:
        - DE
        - US

    yves-build-frontend:
      command: "vendor/bin/console frontend:yves:build"
      stores:
        - DE
        - US

    zed-install-dependencies:
      command: "vendor/bin/console frontend:zed:install-dependencies"
      stores:
        - DE
        - US

    zed-build-frontend:
      command: "vendor/bin/console frontend:zed:build"
      stores:
        - DE
        - US

  scheduler-setup:
    jenkins-generate:
      command: "vendor/bin/console scheduler:setup"
      stores:
        - DE
        - US

  init-storages-per-store:
    setup-search:
      command: "vendor/bin/console setup:search"
      stores:
        - DE
        - US

  init-storages-per-region:
    propel-copy-schema:
      command: "vendor/bin/console propel:schema:copy"
      stores:
        - DE
        - US

    propel-postgres-compatibility:
      command: "vendor/bin/console propel:pg-sql-compat"
      stores:
        - DE
        - US

    propel-migration-delete:
      command: "vendor/bin/console propel:migration:delete"
      stores:
        - DE
        - US

    propel-diff:
      command: "vendor/bin/console propel:diff"
      stores:
        - DE
        - US

    propel-migrate:
      command: "vendor/bin/console propel:migrate"
      stores:
        - DE
        - US

    init-database:
      command: "vendor/bin/console setup:init-db"
      stores:
        - DE
        - US

  demodata:
    import:
      command: "vendor/bin/console data:import"
      stores:
        - DE
        - US

    update-product-labels:
      command: "vendor/bin/console product-label:relations:update"
      stores:
        - DE
        - US
